# Generated by Django 4.1.4 on 2023-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passing_test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedanswers',
            name='real_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passedtests',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='passedtests',
            name='test_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passedtests',
            name='test_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='passedtests',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название теста'),
        ),
    ]
