# Generated by Django 4.1.4 on 2023-01-30 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passing_test', '0003_passedtests_main_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='passedtests',
            name='rait',
            field=models.BooleanField(default=False),
        ),
    ]
