# Generated by Django 4.1.3 on 2022-11-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_tests_creator_alter_tests_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='moderate',
            field=models.CharField(choices=[('OM', 'На проверке'), ('MO', 'Проверено'), ('RE', 'Отказано в публикации')], default='OM', max_length=20, verbose_name='статус'),
        ),
    ]
