# Generated by Django 4.1.4 on 2023-01-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_alter_tests_moderate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='image',
            field=models.ImageField(blank=True, upload_to='tests_images'),
        ),
        migrations.AddField(
            model_name='tests',
            name='raiting',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tests',
            name='visited',
            field=models.IntegerField(default=0),
        ),
    ]
