# Generated by Django 4.1.4 on 2023-01-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_tests_image_tests_raiting_tests_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
