# Generated by Django 4.1.4 on 2023-01-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_tests_questionsnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeoftests',
            name='image',
            field=models.ImageField(blank=True, upload_to='themes_images'),
        ),
    ]
