# Generated by Django 4.1.4 on 2023-01-16 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_themeoftests_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='raiting',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
