# Generated by Django 4.1.4 on 2023-01-24 07:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_alter_tests_raiting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='name',
            field=models.CharField(max_length=600, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='testquestions',
            name='name',
            field=models.CharField(max_length=200, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='tests',
            name='image',
            field=models.ImageField(blank=True, upload_to='tests_images/'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='raiting',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
