# Generated by Django 4.1.4 on 2023-01-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_alter_answers_name_alter_testquestions_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestions',
            name='name',
            field=models.CharField(max_length=600, verbose_name=''),
        ),
    ]
