# Generated by Django 4.1.4 on 2023-01-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_alter_testquestions_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeoftests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='themes_images'),
        ),
    ]
