# Generated by Django 4.1.4 on 2023-01-30 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tests', '0013_alter_themeoftests_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='raiting',
        ),
        migrations.AlterField(
            model_name='themeoftests',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='themes_images/'),
        ),
        migrations.AlterField(
            model_name='themeoftests',
            name='name',
            field=models.CharField(max_length=35, unique=True, verbose_name='Тема теста'),
        ),
        migrations.CreateModel(
            name='Raiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('votes_num', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.tests', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
