# Generated by Django 4.1.4 on 2023-01-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_remove_raiting_votes_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_rait',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
