# Generated by Django 4.1.3 on 2022-11-11 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время добавления')),
                ('tests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.tests')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
