# Generated by Django 4.1.3 on 2022-11-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='state_of_test',
            field=models.BooleanField(default=0),
        ),
    ]
