# Generated by Django 4.1.3 on 2022-11-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0002_office_state_of_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок вакансии')),
                ('href', models.URLField(unique=True)),
                ('company', models.CharField(max_length=250, verbose_name='Компания')),
                ('content', models.TextField(verbose_name='Описание вакансии')),
                ('pay', models.CharField(max_length=50)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
