# Generated by Django 4.1.3 on 2022-11-15 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_tests_creator_alter_tests_name'),
        ('user_office', '0003_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tests.themeoftests'),
        ),
    ]
