# Generated by Django 4.1.3 on 2022-11-15 07:06

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import user_office.models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_tests_creator_alter_tests_name'),
        ('user_office', '0005_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default=user_office.models.default_urls)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.themeoftests')),
            ],
        ),
    ]
