# Generated by Django 4.1.3 on 2022-11-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0006_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url_data',
        ),
        migrations.AddField(
            model_name='url',
            name='href',
            field=models.URLField(null=True, unique=True),
        ),
    ]
