# Generated by Django 4.1.3 on 2022-11-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0007_remove_url_url_data_url_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='site',
            field=models.CharField(default='hh_ru', max_length=100),
        ),
    ]
