# Generated by Django 4.1.3 on 2022-11-15 09:09

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0008_url_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='href',
        ),
        migrations.RemoveField(
            model_name='url',
            name='site',
        ),
        migrations.AddField(
            model_name='url',
            name='url_data',
            field=jsonfield.fields.JSONField(default={'hh.ru': '', 'ya.ru': ''}),
        ),
    ]
