# Generated by Django 4.1.3 on 2022-11-15 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0010_alter_vacancy_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='href',
            field=models.URLField(unique=True),
        ),
    ]
