# Generated by Django 4.1.3 on 2022-11-18 05:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_office', '0011_alter_vacancy_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_data',
            field=jsonfield.fields.JSONField(default={'hh.ru': '', 'job.ru': ''}),
        ),
    ]
